#Application properties
server:
  port: 8081


#AWS properties
cloud:
  aws:
    region:
      static: ap-south-1
    stack:
      auto: false
    credentials:
      accessKey: Paste your access key
      secretKey: Paste your secret key

application:
  bucket:
    name: www.imageupload.awsgayathri

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
